version: '2'
services:
  client:
    image: mhart/alpine-node:latest
    restart: always
    ports:
      - '3000:3000'
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ['npm', 'start']
    # links:
    #   - api
    networks:
      - webappnetwork

  api:
    image: mhart/alpine-node:latest
    restart: always
    ports:
      - '9000:9000'
    working_dir: /api
    volumes:
      - ./api:/api
      # - /api/node_modules
    depends_on:
      - mongodb
    entrypoint: ['npm', 'start']
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge